server:
  port: 8080

spring:
  datasource:
    username: root
    password: mysql123456
    url: jdbc:mysql://127.0.0.1:3306/lottery?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-handlers-package: com.yuanstack.lottery.crypt
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: true

# Dubbo 广播方式配置
dubbo:
  application:
    name: lottery
    version: 1.0.0
  registry:
    address: N/A #multicast://224.5.6.7:1234
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.yuanstack.lottery.rpc
